# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170420_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=3)),
                ('nickname', models.CharField(max_length=14)),
                ('mail', models.EmailField(max_length=50, unique=True)),
                ('attendance', models.CharField(choices=[('yes', 'Online'), ('no', 'Offline')], max_length=7)),
                ('comment', models.TextField()),
                ('registation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
