# Generated by Django 2.0.1 on 2018-02-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170802_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreg',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete='id', to='events.Events'),
        ),
    ]
