# Generated by Django 2.0.1 on 2018-02-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventreg_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreg',
            name='event',
        ),
    ]
