# Generated by Django 2.0.1 on 2018-02-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_eventreg_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreg',
            name='registation_date',
        ),
        migrations.AddField(
            model_name='eventreg',
            name='registration_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
