# Generated by Django 2.0.1 on 2018-02-25 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180222_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreg',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
    ]
