# Generated by Django 2.0.1 on 2018-02-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventreg_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreg',
            name='event',
        ),
    ]
