# Generated by Django 2.0.1 on 2018-02-25 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_eventreg_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreg',
            name='reg_to',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
    ]
