# Generated by Django 2.0.1 on 2018-02-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventreg_reg_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreg',
            name='reg_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Events'),
        ),
    ]
