# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=1)),
                ('range', models.CharField(max_length=4)),
                ('damage', models.CharField(max_length=5)),
                ('xm', models.CharField(max_length=5)),
            ],
        ),
    ]
