# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0003_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='description',
            field=models.TextField(help_text='Полное, или доступное, описание предмета или его действий'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.ImageField(upload_to='ingr/static/images/weapons'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(help_text='Название оружия', max_length=255),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('Virus', 'Захватывающее'), ('Weapon', 'Разрушающее')], default='Weapon', help_text='Выберите тип оружия Разрущающее или Захватывающее', max_length=6),
        ),
    ]
