# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0005_auto_20170420_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='posititon',
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('Virus', 'Захватывающее'), ('Weapon', 'Разрушающее')], default='Weapon', help_text='Выберите тип оружия Разрущающее или Захватывающее', max_length=6),
        ),
    ]
