# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0006_auto_20170420_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('xmp_use', models.TextField(blank=True, null=True)),
                ('ultra_xmp_use', models.TextField(blank=True, null=True)),
                ('virus_use', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gameplay/')),
            ],
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.ImageField(upload_to='weapons/'),
        ),
    ]
