# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0007_auto_20170425_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameplayImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gameplay/')),
            ],
        ),
        migrations.AlterField(
            model_name='instruction',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapon.GameplayImage'),
        ),
    ]
