# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0009_gameplayimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayimage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
