# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapon', '0010_auto_20170425_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='image',
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='weapons/'),
        ),
        migrations.DeleteModel(
            name='GameplayImage',
        ),
    ]
