# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=10)),
                ('descriprion', models.CharField(max_length=255)),
                ('common', models.CharField(max_length=5)),
                ('rare', models.CharField(max_length=5)),
                ('very_rare', models.CharField(max_length=5)),
                ('image', models.ImageField(height_field=100, upload_to='', width_field=100)),
            ],
        ),
    ]
