# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mods',
            name='common',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='mods',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='mods',
            name='rare',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mods',
            name='very_rare',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
