# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_auto_20170419_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название модификатора', max_length=200)),
                ('short_name', models.CharField(help_text='Короткое описание', max_length=10)),
                ('descriprion', models.TextField(help_text='Полное, или доступное, описания предмета иил его действия')),
                ('common', models.CharField(blank=True, help_text='Степень воздействия если предмет очень частый ', max_length=5)),
                ('rare', models.CharField(blank=True, help_text='Степень воздействия если предмет редкий', max_length=50)),
                ('very_rare', models.CharField(blank=True, help_text='Степень воздействия если предмет очень редкий', max_length=50)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Mods',
        ),
    ]
