# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0004_auto_20170420_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='instruction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mod',
            name='practice',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='image',
            field=models.ImageField(upload_to='mods/'),
        ),
    ]
