# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0008_auto_20170424_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='deploy',
        ),
        migrations.AddField(
            model_name='instruction',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Deploy'),
        ),
    ]
