# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0010_auto_20170424_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='name',
            field=models.CharField(default='Описания и рекоммендации', max_length=255),
        ),
    ]
