# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0011_auto_20170424_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
